In [4]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression

col_names=['pregnant','glucose','bp','skin','insulin','bmi','pedigree','age','label']

pima=pd.read_csv('diabetes.csv',header=1,names=col_names)
pima.head()

pregnant  glucose  bp  skin  insulin   bmi  pedigree  age  label
0         1       85  66    29        0  26.6     0.351   31      0
1         8      183  64     0        0  23.3     0.672   32      1
2         1       89  66    23       94  28.1     0.167   21      0
3         0      137  40    35      168  43.1     2.288   33      1
4         5      116  74     0        0  25.6     0.201   30      0

In [5]:
feature_cols=['pregnant','insulin','bmi','age','glucose','bp','pedigree']
X=pima[feature_cols]
y=pima.label

In [6]:
X.head()

pregnant  insulin   bmi  age  glucose  bp  pedigree
0         1        0  26.6   31       85  66     0.351
1         8        0  23.3   32      183  64     0.672
2         1       94  28.1   21       89  66     0.167
3         0      168  43.1   33      137  40     2.288
4         5        0  25.6   30      116  74     0.201

In [7]:
y.head()

0    0
1    1
2    0
3    1
4    0
Name: label, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

In [9]:
X_train=np.array(X_train)[np.array(y_train)!='Outcome']

C:\Users\taehwan\AppData\Local\Temp\ipykernel_35768\3268556251.py:1: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  X_train=np.array(X_train)[np.array(y_train)!='Outcome']


In [10]:
y_train=np.array(y_train)[np.array(y_train)!='Outcome']

C:\Users\taehwan\AppData\Local\Temp\ipykernel_35768\1818094446.py:1: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  y_train=np.array(y_train)[np.array(y_train)!='Outcome']


In [12]:
X_train=X_train[0]
y_train=y_train[0]

In [13]:
X_train

array([[1.00e+01, 1.80e+02, 3.29e+01, ..., 1.01e+02, 7.60e+01, 1.71e-01],
       [1.00e+00, 1.45e+02, 3.45e+01, ..., 1.17e+02, 8.80e+01, 4.03e-01],
       [2.00e+00, 8.80e+01, 2.61e+01, ..., 9.50e+01, 5.40e+01, 7.48e-01],
       ...,
       [7.00e+00, 0.00e+00, 2.74e+01, ..., 1.14e+02, 6.40e+01, 7.32e-01],
       [6.00e+00, 0.00e+00, 3.38e+01, ..., 1.25e+02, 7.60e+01, 1.21e-01],
       [2.00e+00, 2.05e+02, 3.32e+01, ..., 1.29e+02, 7.40e+01, 5.91e-01]])

In [14]:
y_train

array([0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,

In [15]:
X_test=np.array(X_test)
y_test=np.array(y_test)

In [16]:
X_test

array([[8.000e+00, 2.310e+02, 3.760e+01, ..., 1.670e+02, 1.060e+02,
        1.650e-01],
       [5.000e+00, 0.000e+00, 2.680e+01, ..., 1.320e+02, 8.000e+01,
        1.860e-01],
       [7.000e+00, 1.750e+02, 3.050e+01, ..., 1.600e+02, 5.400e+01,
        5.880e-01],
       ...,
       [1.000e+00, 5.900e+01, 2.510e+01, ..., 9.000e+01, 6.200e+01,
        1.268e+00],
       [5.000e+00, 0.000e+00, 3.950e+01, ..., 1.060e+02, 8.200e+01,
        2.860e-01],
       [1.000e+01, 0.000e+00, 2.400e+01, ..., 1.150e+02, 9.800e+01,
        1.022e+00]])

In [17]:
y_test

array([1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [18]:
logreg=LogisticRegression()

logreg.fit(X_train,y_train)
y_pred=logreg.predict(X_test)

c:\Users\taehwan\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [19]:
y_pred

array([1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [20]:
y_test==y_pred

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True, False, False,
        True,  True,  True, False,  True,  True,  True, False, False,
        True,  True,  True, False,  True,  True, False, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True, False,  True,  True,  True,  True, False,
       False,  True,  True,  True, False,  True,  True,  True, False,
        True, False,  True,  True,  True, False, False,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True, False,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
       False, False,

In [21]:
np.mean(y_test==y_pred)

0.796875

In [22]:
from sklearn import metrics
cnf_matrix=metrics.confusion_matrix(y_test,y_pred)
cnf_matrix

array([[118,  13],
       [ 26,  35]], dtype=int64)