In [1]:
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

#데이터를 읽어오기
like = pd.read_csv('like.csv')
like.columns = ['talk' , 'book' , 'travel' , 'school' , 'tall' , 'skin' , 'muscle' , 'like_level']
like.head() 

talk  book  travel  school  tall  skin  muscle like_level
0    30    80      40      40    90    90      50        1타입
1    60    50      70      50    60    60      90        2타입
2    50    40      80      60    50    70      80        2타입
3    90    50      60      30    40    20      30        3타입
4    50    70      30      70    70    80      60        1타입

In [2]:
#입력과 target데이터를 분리한다. 
x = np.array(like.drop('like_level', axis=1))
print(x.shape)
y = np.array(like.like_level)
print(y.shape)

(14, 7)
(14,)


In [3]:
y.shape , x.shape

((14,), (14, 7))

In [4]:
#데이터를 정규화한다. 
from sklearn.preprocessing import StandardScaler  
scaler = StandardScaler()  
scaler.fit(x)

x = scaler.transform(x)

In [5]:
x

array([[-1.26962211,  1.34164079, -0.8461218 , -0.98782916,  2.06644812,
         1.29927838, -0.59160798],
       [ 0.21160368, -0.36590203,  0.57536283, -0.3592106 ,  0.04805693,
        -0.09994449,  1.77482393],
       [-0.28213825, -0.93508297,  1.04919104,  0.26940795, -0.62474013,
         0.36646313,  1.18321596],
       [ 1.69282948, -0.36590203,  0.10153462, -1.61644772, -1.29753719,
        -1.96557498, -1.77482393],
       [-0.28213825,  0.77245985, -1.31995001,  0.89802651,  0.720854  ,
         0.83287076,  0.        ],
       [ 0.70534562, -1.50426391,  0.10153462, -0.98782916, -1.29753719,
        -1.03275974, -1.77482393],
       [-0.77588018,  1.91082173,  0.10153462,  0.26940795,  0.04805693,
         0.83287076,  0.        ],
       [-1.26962211,  0.20327891,  1.52301925,  0.26940795, -1.29753719,
         0.36646313,  0.59160798],
       [ 1.19908755, -0.93508297, -1.79377823,  1.52664507,  0.04805693,
        -1.03275974, -0.59160798],
       [-0.28213825,  0.7724

In [6]:
#knn 분류기 모델을 만든다. 
from sklearn.neighbors import KNeighborsClassifier  
classifier = KNeighborsClassifier(n_neighbors=5)  
classifier.fit(x, y)  

KNeighborsClassifier()

In [7]:
#원래의 데이터를 넣어서 예측한다. 
y_pred = classifier.predict(x)  
y_pred

array(['1타입', '2타입', '2타입', '3타입', '1타입', '3타입', '1타입', '2타입', '3타입',
       '1타입', '3타입', '1타입', '2타입', '3타입'], dtype=object)

In [8]:
y

array(['1타입', '2타입', '2타입', '3타입', '1타입', '3타입', '1타입', '2타입', '3타입',
       '1타입', '3타입', '1타입', '2타입', '3타입'], dtype=object)

In [9]:
#모델을 평가한다. 
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y, y_pred))  
print(classification_report(y, y_pred))  

[[5 0 0]
 [0 4 0]
 [0 0 5]]
              precision    recall  f1-score   support

         1타입       1.00      1.00      1.00         5
         2타입       1.00      1.00      1.00         4
         3타입       1.00      1.00      1.00         5

    accuracy                           1.00        14
   macro avg       1.00      1.00      1.00        14
weighted avg       1.00      1.00      1.00        14

